<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Interesting throw/catch behaviour in Ruby | Janko's Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Begin Jekyll SEO tag v2.7.1 -->
<meta name="generator" content="Jekyll v4.3.1" />
<meta property="og:title" content="Interesting throw/catch behaviour in Ruby" />
<meta name="author" content="Janko MarohniÄ‡" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="When I was working on integrating Rodauth with OmniAuth authentication, I noticed an error warning after upgrading to Rails 6.1, when Rodauth was redirecting inside a Rails controller action:" />
<meta property="og:description" content="When I was working on integrating Rodauth with OmniAuth authentication, I noticed an error warning after upgrading to Rails 6.1, when Rodauth was redirecting inside a Rails controller action:" />
<link rel="canonical" href="https://janko.io/interesting-throw-catch-behaviour-in-ruby/" />
<meta property="og:url" content="https://janko.io/interesting-throw-catch-behaviour-in-ruby/" />
<meta property="og:site_name" content="Jankoâ€™s Blog" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2021-01-24T00:00:00+01:00" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Interesting throw/catch behaviour in Ruby" />
<meta name="twitter:site" content="@jankomarohnic" />
<meta name="twitter:creator" content="@jankomarohnic" />
<meta property="article:publisher" content="https://www.facebook.com/janko.marohnic/" />
<script type="application/ld+json">
{"@type":"BlogPosting","headline":"Interesting throw/catch behaviour in Ruby","dateModified":"2021-01-24T00:00:00+01:00","description":"When I was working on integrating Rodauth with OmniAuth authentication, I noticed an error warning after upgrading to Rails 6.1, when Rodauth was redirecting inside a Rails controller action:","datePublished":"2021-01-24T00:00:00+01:00","mainEntityOfPage":{"@type":"WebPage","@id":"https://janko.io/interesting-throw-catch-behaviour-in-ruby/"},"publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":"https://janko.io/images/logo.png"},"name":"Janko MarohniÄ‡"},"url":"https://janko.io/interesting-throw-catch-behaviour-in-ruby/","author":{"@type":"Person","name":"Janko MarohniÄ‡"},"@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <link type="application/atom+xml" rel="alternate" href="https://janko.io/feed.xml" title="Janko&apos;s Blog" />
    <link rel="stylesheet" href="/css/bundle.css">
  </head>

  <body class="text-xl text-gray-700 dark:bg-slate-900 dark:text-gray-400">
    <header class="py-3 px-4 flex flex-col space-y-1 bg-gray-100 border-b dark:bg-gray-800/70 dark:border-sky-300">
      <div class="flex justify-center">
        <a class="flex items-center space-x-2" href="/">
          <img class="h-8" src="/images/logo.png" alt="logo" />
          <span class="text-2xl md:text-3xl font-semibold text-pink-700 dark:text-pink-500">Janko's Blog</span>
        </a>
      </div>
      <div class="flex justify-center">
        <span class="text-base md:text-lg text-gray-500 dark:text-gray-400">Sharing the wonders of Ruby</p>
      </div>
    </header>

    <div class="text-center py-3 px-4 bg-sky-50 border-b border-sky-100 text-sky-600 text-base md:text-md lg:text-lg dark:text-sky-300 dark:bg-sky-900/40 dark:border-sky-300">
      Dear Russian friends, please watch President Zelenskyy's <a href="https://www.youtube.com/watch?v=p-zilnPtZ2M" class="underline text-blue-600 hover:text-blue-500 dark:text-blue-500 dark:hover:text-blue-400">speech addressed to you</a>.
      ðŸ‡ºðŸ‡¦ Support Ukraine by <a href="https://war.ukraine.ua/support-ukraine/" class="underline text-yellow-600 hover:text-yellow-500 dark:text-yellow-500 dark:hover:text-yellow-400">donating</a> to humanitarian aid.
    </div>

    <div class="my-6 sm:my-8 mx-4">
      <main class="max-w-screen-sm md:max-w-screen-md mx-auto">
        <article>
  <header class="space-y-4 md:space-y-5">
    <h1 class="lg:-mx-28 text-3xl sm:text-4xl lg:text-5xl text-center font-medium text-gray-900 dark:text-gray-100">Interesting throw/catch behaviour in Ruby</h1>

    <div class="flex justify-center">
      <div class="flex flex-col items-center sm:flex-row sm:items-baseline space-y-3 sm:space-y-0 sm:space-x-4 text-sm md:text-base">
        <span class="text-gray-500 dark:text-gray-400">
          By <a class="underline hover:text-gray-300" href="/about">Janko MarohniÄ‡</a> on
          <time datetime="2021-01-24 00:00:00 +0100">
            24 Jan 2021
          </time>
        </span>
        
          
<a class="my-1 rounded-full px-3 bg-teal-100 text-teal-700 font-semibold py-0.5 dark:bg-teal-900 dark:text-teal-300" href="/til">til</a>


        
      </div>
    </div>
  </header>

  <div class="mt-4 sm:mt-6 markdown">
    <p>When I was working on integrating <a href="https://github.com/jeremyevans/rodauth">Rodauth</a> with OmniAuth authentication, I
noticed an error warning after upgrading to Rails 6.1, when Rodauth was
redirecting inside a Rails controller action:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">RodauthController</span> <span class="o">&lt;</span> <span class="no">ApplicationController</span>
  <span class="k">def</span> <span class="nf">omniauth</span>
    <span class="c1"># ...</span>
    <span class="n">rodauth</span><span class="p">.</span><span class="nf">login</span><span class="p">(</span><span class="s2">"omniauth"</span><span class="p">)</span> <span class="c1"># logs the session in and redirects</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div></div>
<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Could not log "process_action.action_controller" event.
/path/to/actionpack-6.1.1/lib/action_controller/log_subscriber.rb:26:in `block in process_action': undefined method `first' for nil:NilClass (NoMethodError)
</code></pre></div></div>

<p>Since I want the integration between Rodauth and Rails to be as smooth as
possible, I decided to investigate.</p>

<h2 id="diving-in">Diving in</h2>

<p>Letâ€™s see the <code class="language-plaintext highlighter-rouge">ActionController::LogSubscriber</code> source code where the error
happens:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1"># lib/action_controller/log_subscriber.rb</span>
<span class="k">module</span> <span class="nn">ActionController</span>
  <span class="k">class</span> <span class="nc">LogSubscriber</span> <span class="o">&lt;</span> <span class="no">ActiveSupport</span><span class="o">::</span><span class="no">LogSubscriber</span>
    <span class="c1"># ...</span>
    <span class="k">def</span> <span class="nf">process_action</span><span class="p">(</span><span class="n">event</span><span class="p">)</span>
      <span class="c1"># ...</span>
        <span class="n">status</span> <span class="o">=</span> <span class="n">payload</span><span class="p">[</span><span class="ss">:status</span><span class="p">]</span>

        <span class="k">if</span> <span class="n">status</span><span class="p">.</span><span class="nf">nil?</span> <span class="o">&amp;&amp;</span> <span class="p">(</span><span class="n">exception_class_name</span> <span class="o">=</span> <span class="n">payload</span><span class="p">[</span><span class="ss">:exception</span><span class="p">].</span><span class="nf">first</span><span class="p">)</span> <span class="c1"># &lt;==== the exception happens here</span>
          <span class="n">status</span> <span class="o">=</span> <span class="no">ActionDispatch</span><span class="o">::</span><span class="no">ExceptionWrapper</span><span class="p">.</span><span class="nf">status_code_for_exception</span><span class="p">(</span><span class="n">exception_class_name</span><span class="p">)</span>
        <span class="k">end</span>
      <span class="c1"># ...</span>
    <span class="k">end</span>
    <span class="c1"># ...</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div></div>

<p>We can see that the issue happens because <code class="language-plaintext highlighter-rouge">:exception</code> data is missing from the
instrumentation event payload. Letâ€™s look at
<code class="language-plaintext highlighter-rouge">ActionController::Instrumentation</code> next, which is in charge of instrumenting
controller actions:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1"># lib/action_controller/metal/instrumentation.rb</span>
<span class="k">class</span> <span class="nc">ActionController</span>
  <span class="k">module</span> <span class="nn">Instrumentation</span>
    <span class="k">def</span> <span class="nf">process_action</span><span class="p">(</span><span class="o">*</span><span class="p">)</span>
      <span class="c1"># ...</span>
      <span class="no">ActiveSupport</span><span class="o">::</span><span class="no">Notifications</span><span class="p">.</span><span class="nf">instrument</span><span class="p">(</span><span class="s2">"process_action.action_controller"</span><span class="p">,</span> <span class="n">raw_payload</span><span class="p">)</span> <span class="k">do</span> <span class="o">|</span><span class="n">payload</span><span class="o">|</span>
        <span class="n">result</span> <span class="o">=</span> <span class="k">super</span> <span class="c1"># &lt;=== this calls our controller action</span>
        <span class="n">payload</span><span class="p">[</span><span class="ss">:response</span><span class="p">]</span> <span class="o">=</span> <span class="n">response</span>
        <span class="n">payload</span><span class="p">[</span><span class="ss">:status</span><span class="p">]</span>   <span class="o">=</span> <span class="n">response</span><span class="p">.</span><span class="nf">status</span>
        <span class="c1"># ...</span>
      <span class="k">end</span>
    <span class="k">end</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div></div>

<p>We can see that, if our controller action raises an exception, the <code class="language-plaintext highlighter-rouge">:status</code>
data will never be set. This ties to the <code class="language-plaintext highlighter-rouge">status.nil?</code> check weâ€™ve seen in the
<code class="language-plaintext highlighter-rouge">ActionController::LogSubscriber</code>.</p>

<p>The remaining part is to find where <code class="language-plaintext highlighter-rouge">:exception</code> is being set. Knowing that
instrumentation is implemented in Active Support, I quickly found
<code class="language-plaintext highlighter-rouge">ActiveSupport::Notifications::Instrumenter</code>:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1"># lib/active_support/notifications/instrumenter.rb</span>
<span class="k">module</span> <span class="nn">ActiveSupport</span>
  <span class="k">module</span> <span class="nn">Notifications</span>
    <span class="k">class</span> <span class="nc">Instrumenter</span>
      <span class="c1"># ...</span>
      <span class="k">def</span> <span class="nf">instrument</span><span class="p">(</span><span class="nb">name</span><span class="p">,</span> <span class="n">payload</span> <span class="o">=</span> <span class="p">{})</span>
        <span class="c1"># ...</span>
        <span class="k">begin</span>
          <span class="k">yield</span> <span class="n">payload</span> <span class="k">if</span> <span class="nb">block_given?</span>
        <span class="k">rescue</span> <span class="no">Exception</span> <span class="o">=&gt;</span> <span class="n">e</span>
          <span class="n">payload</span><span class="p">[</span><span class="ss">:exception</span><span class="p">]</span> <span class="o">=</span> <span class="p">[</span><span class="n">e</span><span class="p">.</span><span class="nf">class</span><span class="p">.</span><span class="nf">name</span><span class="p">,</span> <span class="n">e</span><span class="p">.</span><span class="nf">message</span><span class="p">]</span> <span class="c1"># &lt;==== the exception is set here</span>
          <span class="n">payload</span><span class="p">[</span><span class="ss">:exception_object</span><span class="p">]</span> <span class="o">=</span> <span class="n">e</span>
          <span class="k">raise</span> <span class="n">e</span>
        <span class="k">ensure</span>
          <span class="n">finish_with_state</span> <span class="n">listeners_state</span><span class="p">,</span> <span class="nb">name</span><span class="p">,</span> <span class="n">payload</span>
        <span class="k">end</span>
      <span class="k">end</span>
    <span class="k">end</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div></div>

<h2 id="the-problem">The problem</h2>

<p>When Rodauth redirects, what is actually doing is throwing <code class="language-plaintext highlighter-rouge">:halt</code> with the
rack response. This is how Roda implements redirection, and itâ€™s common practice
in non-Rails web frameworks (Sinatra and Cuba do it too). In our case, throwing
exits from controller action and is caught by the Roda middleware.</p>

<p>Does throwing act the same way as raising an exception does? Initially it
would appear so:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">begin</span>
  <span class="kp">throw</span> <span class="ss">:halt</span>
<span class="k">rescue</span> <span class="no">Exception</span> <span class="o">=&gt;</span> <span class="n">exception</span>
  <span class="nb">puts</span> <span class="s2">"rescue: </span><span class="si">#{</span><span class="n">exception</span><span class="p">.</span><span class="nf">inspect</span><span class="si">}</span><span class="s2">"</span>
  <span class="k">raise</span>
<span class="k">ensure</span>
  <span class="nb">puts</span> <span class="s2">"ensure"</span>
<span class="k">end</span>
</code></pre></div></div>
<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>rescue: #&lt;UncaughtThrowError: uncaught throw :halt&gt;
ensure
~&gt; uncaught throw :halt (UncaughtThrowError)
</code></pre></div></div>

<p>This makes sense to me, because uncaught throw <em>is</em> an exception. But then why
wasnâ€™t the <code class="language-plaintext highlighter-rouge">rescue</code> block that was supposed to set the <code class="language-plaintext highlighter-rouge">:exception</code> in the
event payload being executed?</p>

<p>The picture starts getting clearer when we wrap the code with a <code class="language-plaintext highlighter-rouge">catch</code>
block:</p>

<div class="language-rb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kp">catch</span><span class="p">(</span><span class="ss">:halt</span><span class="p">)</span> <span class="k">do</span>
  <span class="k">begin</span>
    <span class="kp">throw</span> <span class="ss">:halt</span>
  <span class="k">rescue</span> <span class="no">Exception</span> <span class="o">=&gt;</span> <span class="n">exception</span>
    <span class="nb">puts</span> <span class="s2">"rescue: </span><span class="si">#{</span><span class="n">exception</span><span class="p">.</span><span class="nf">inspect</span><span class="si">}</span><span class="s2">"</span>
    <span class="k">raise</span>
  <span class="k">ensure</span>
    <span class="nb">puts</span> <span class="s2">"ensure"</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div></div>
<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>ensure
</code></pre></div></div>

<p>We see that in this case the <code class="language-plaintext highlighter-rouge">rescue</code> block isnâ€™t being executed, and this is
precisely our scenario. This actually makes sense when you think about it,
because a <code class="language-plaintext highlighter-rouge">throw</code> with a matching <code class="language-plaintext highlighter-rouge">catch</code> is not anything erroneous, itâ€™s just
a way to do an early return.</p>

<h2 id="the-solution">The solution</h2>

<p>Now we know where the issue is, which is that Rails just wasnâ€™t correctly
handling a <code class="language-plaintext highlighter-rouge">throw</code>/<code class="language-plaintext highlighter-rouge">catch</code> scenario when processing controller actions. <a href="https://github.com/rails/rails/pull/41223">Fixing
it</a> was the easy part.</p>

<p><code class="language-plaintext highlighter-rouge">throw</code>/<code class="language-plaintext highlighter-rouge">catch</code> is probably something youâ€™ll rarely use, but it does have its
use cases. I hope this article taught you a bit more about this lesser known
Ruby feature.</p>


  </div>
</article>

<div class="mt-8 md:mt-10">
  
  <script src="https://utteranc.es/client.js"
          repo="janko/janko.io"
          issue-term="title"
          theme="preferred-color-scheme"
          crossorigin="anonymous"
          async>
  </script>


</div>

      </main>
    </div>

    
      <!-- Fathom - beautiful, simple website analytics -->
<script src="https://bouncy-van.janko.io/script.js" data-site="EKJCVCTX" defer></script>
<!-- / Fathom -->

    
  </body>
</html>
